apiVersion: v1
kind: Service
metadata:
  name: node-port-eureka-server
spec:
  type: NodePort
  selector:
    component: eureka-server-microservice-v1
  ports:
    - port: 8888
      targetPort: 8888 
      nodePort: 31122