apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-eureka-server
spec:
  type: ClusterIP
  selector:
    component: eureka-server-microservice-v1
  ports:
    - port: 8888
      targetPort: 8888
