apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-country-server
spec:
  type: ClusterIP
  selector:
    component: country-server-microservice-v1
  ports:
    - port: 9000
      targetPort: 9000
