apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-country-client
spec:
  type: ClusterIP
  selector:
    component: country-client-v1
  ports:
    - port: 9090
      targetPort: 9090
