apiVersion: v1
kind: Service
metadata:
  name: node-port-country-client
spec:
  type: NodePort
  selector:
    component: country-client-v1
  ports:
    - port: 9090
      targetPort: 9090 
      nodePort: 31121